# Generated by Django 4.1.7 on 2023-02-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('cnfm_password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Register',
                'verbose_name_plural': 'Registrations',
            },
        ),
    ]
